### ISSUE TITLE
18.1.2 might be broken

### ISSUE THREAD

**Issue by plowsof** [sethforprivacy/simple-monero-wallet-rpc-docker#26]
i and 2 others have reported an issue with the latest version, might be worth having a look

**Comment by sethforprivacy** [comment]
@plowsof What is broken about it? I don't actually use this image for anything so any detail you can provide would be extremely helpful here.

**Comment by plowsof** [comment]
i will confirm exactly whats happening and report back (i assumed it was my cache) iirc when trying "./monero-wallet-rpc" in the docker it "doesnt exist" even though it's there. and the owner/group was "1000"
