### ISSUE TITLE
Mount Wallet from Host

### ISSUE THREAD

**Issue by 0-don** [sethforprivacy/simple-monero-wallet-rpc-docker#33]
How do you mount or create wallet from outside ?
this doesnt seem to work
```yml
    volumes:
      - ./wallet:/home/monero/wallet
```
      
because I get this error

```json
{
    "error": {
        "code": -1,
        "message": "failed to save file \"/home/monero/wallet/monero.keys\""
    },
    "id": "0",
    "jsonrpc": "2.0"
}
```

**Comment by hundehausen** [comment]
https://github.com/sethforprivacy/simple-monerod-docker/blob/main/Dockerfile#L155

User in the container is monero:monero and that differs from your host user. This might cause the issue.
